% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Assignment 7: GLMs (Linear Regressios, ANOVA, \& t-tests)},
  pdfauthor={Logan Loadholtz},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=2.54cm]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering

\title{Assignment 7: GLMs (Linear Regressios, ANOVA, \& t-tests)}
\author{Logan Loadholtz}
\date{}

\begin{document}
\maketitle

\hypertarget{overview}{%
\subsection{OVERVIEW}\label{overview}}

This exercise accompanies the lessons in Environmental Data Analytics on
generalized linear models.

\hypertarget{directions}{%
\subsection{Directions}\label{directions}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Change ``Student Name'' on line 3 (above) with your name.
\item
  Work through the steps, \textbf{creating code and output} that fulfill
  each instruction.
\item
  Be sure to \textbf{answer the questions} in this assignment document.
\item
  When you have completed the assignment, \textbf{Knit} the text and
  code into a single PDF file.
\item
  After Knitting, submit the completed exercise (PDF file) to the
  dropbox in Sakai. Add your last name into the file name (e.g.,
  ``Fay\_A06\_GLMs.Rmd'') prior to submission.
\end{enumerate}

The completed exercise is due on Tuesday, March 2 at 1:00 pm.

\hypertarget{set-up-your-session}{%
\subsection{Set up your session}\label{set-up-your-session}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Set up your session. Check your working directory. Load the tidyverse,
  agricolae and other needed packages. Import the \emph{raw} NTL-LTER
  raw data file for chemistry/physics
  (\texttt{NTL-LTER\_Lake\_ChemistryPhysics\_Raw.csv}). Set date columns
  to date objects.
\item
  Build a ggplot theme and set it as your default theme.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#1}
\KeywordTok{getwd}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "/Users/loganloadholtz/Documents/DATA/Environmental_Data_Analytics_2021"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#install.packages("htmltools")}
\KeywordTok{library}\NormalTok{(htmltools)}
\CommentTok{#install.packages("agricolae")}
\KeywordTok{library}\NormalTok{(agricolae)}
\KeywordTok{library}\NormalTok{(tidyverse)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## -- Attaching packages -------------------------------------------------------------- tidyverse 1.3.0 --
\end{verbatim}

\begin{verbatim}
## v ggplot2 3.3.2     v purrr   0.3.4
## v tibble  3.0.3     v dplyr   1.0.2
## v tidyr   1.1.2     v stringr 1.4.0
## v readr   1.3.1     v forcats 0.5.0
\end{verbatim}

\begin{verbatim}
## -- Conflicts ----------------------------------------------------------------- tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(lubridate)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'lubridate'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:base':
## 
##     date, intersect, setdiff, union
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(ggplot2)}

\CommentTok{#importing data}
\NormalTok{NTL_LTER_Lake_Chemistry_Physics_Raw <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"./Data/Raw/NTL-LTER_Lake_ChemistryPhysics_Raw.csv"}\NormalTok{, }
                                                \DataTypeTok{stringsAsFactors =} \OtherTok{FALSE}\NormalTok{)}

\CommentTok{#find class of sample date, it is character}
\KeywordTok{class}\NormalTok{(NTL_LTER_Lake_Chemistry_Physics_Raw}\OperatorTok{$}\NormalTok{sampledate)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "character"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#format sampledate as DATE}
\NormalTok{NTL_LTER_Lake_Chemistry_Physics_Raw}\OperatorTok{$}\NormalTok{sampledate <-}\StringTok{ }\KeywordTok{as.Date}\NormalTok{(NTL_LTER_Lake_Chemistry_Physics_Raw}\OperatorTok{$}\NormalTok{sampledate, }
                                                          \DataTypeTok{format=} \StringTok{"%m/%d/%y"}\NormalTok{)}

\CommentTok{#sampledate is now in Date form}
\KeywordTok{class}\NormalTok{(NTL_LTER_Lake_Chemistry_Physics_Raw}\OperatorTok{$}\NormalTok{sampledate)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Date"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#2}
\NormalTok{mytheme <-}\StringTok{ }\KeywordTok{theme_classic}\NormalTok{(}\DataTypeTok{base_size =} \DecValTok{14}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.text =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{color =} \StringTok{"black"}\NormalTok{), }
        \DataTypeTok{legend.position =} \StringTok{"top"}\NormalTok{)}
\KeywordTok{theme_set}\NormalTok{(mytheme)}
\end{Highlighting}
\end{Shaded}

\hypertarget{simple-regression}{%
\subsection{Simple regression}\label{simple-regression}}

Our first research question is: Does mean lake temperature recorded
during July change with depth across all lakes?

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\item
  State the null and alternative hypotheses for this question:
  \textgreater{} Answer: H0: Mean lake temperature recorded during July
  does not change with depth across all Lakes Ha: Mean lake temperature
  recorded during July changes with depth across all lakes
\item
  Wrangle your NTL-LTER dataset with a pipe function so that the records
  meet the following criteria:
\end{enumerate}

\begin{itemize}
\tightlist
\item
  Only dates in July.
\item
  Only the columns: \texttt{lakename}, \texttt{year4}, \texttt{daynum},
  \texttt{depth}, \texttt{temperature\_C}
\item
  Only complete cases (i.e., remove NAs)
\end{itemize}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{4}
\tightlist
\item
  Visualize the relationship among the two continuous variables with a
  scatter plot of temperature by depth. Add a smoothed line showing the
  linear model, and limit temperature values from 0 to 35 °C. Make this
  plot look pretty and easy to read.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#4}

\NormalTok{NTL_Processed <-}\StringTok{ }\NormalTok{NTL_LTER_Lake_Chemistry_Physics_Raw }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(daynum }\OperatorTok{>}\DecValTok{181} \OperatorTok{&}\StringTok{ }\NormalTok{daynum }\OperatorTok{<}\DecValTok{213}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{select}\NormalTok{(lakename, year4, daynum, depth, temperature_C) }\OperatorTok{%>%}
\StringTok{  }\NormalTok{na.omit}
  

\CommentTok{#5}
\NormalTok{Plot_Temp_Depth <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(NTL_Processed, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{depth, }\DataTypeTok{y=}\NormalTok{temperature_C)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_point}\NormalTok{()}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_smooth}\NormalTok{(}\DataTypeTok{method =}\NormalTok{ lm, }\DataTypeTok{color=}\StringTok{"black"}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{ylim}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{35}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\StringTok{"Depth"}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{(}\StringTok{"Temperature in Celcius"}\NormalTok{)}

\KeywordTok{print}\NormalTok{(Plot_Temp_Depth)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula 'y ~ x'
\end{verbatim}

\begin{verbatim}
## Warning: Removed 24 rows containing missing values (geom_smooth).
\end{verbatim}

\includegraphics{A06_GLMs_files/figure-latex/scatterplot-1.pdf}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{5}
\tightlist
\item
  Interpret the figure. What does it suggest with regards to the
  response of temperature to depth? Do the distribution of points
  suggest about anything about the linearity of this trend?
\end{enumerate}

\begin{quote}
Answer: According to the line, there is a general negative trend between
temperature and depth- the deeper the water, the lower the temperature
is. However, with a closer look, this distribution shows that most of
the points appear to be distributed towards lower depths, meaning that
at lower depths, there can actually have quite a wide range of
temperatures. As depth increases, temperature varies much less.
\end{quote}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{6}
\tightlist
\item
  Perform a linear regression to test the relationship and display the
  results
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#7}

\NormalTok{LTR_regression <-}\StringTok{ }\KeywordTok{lm}\NormalTok{(NTL_Processed}\OperatorTok{$}\NormalTok{temperature_C }\OperatorTok{~}\StringTok{ }\NormalTok{NTL_Processed}\OperatorTok{$}\NormalTok{depth)}

\KeywordTok{summary}\NormalTok{(LTR_regression)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = NTL_Processed$temperature_C ~ NTL_Processed$depth)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -9.5077 -3.0182  0.0743  2.9248 13.6033 
## 
## Coefficients:
##                     Estimate Std. Error t value Pr(>|t|)    
## (Intercept)         21.94872    0.06790   323.3   <2e-16 ***
## NTL_Processed$depth -1.94700    0.01173  -166.0   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 3.829 on 9720 degrees of freedom
## Multiple R-squared:  0.7391, Adjusted R-squared:  0.7391 
## F-statistic: 2.754e+04 on 1 and 9720 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{cor.test}\NormalTok{(NTL_Processed}\OperatorTok{$}\NormalTok{temperature_C, NTL_Processed}\OperatorTok{$}\NormalTok{depth)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Pearson's product-moment correlation
## 
## data:  NTL_Processed$temperature_C and NTL_Processed$depth
## t = -165.96, df = 9720, p-value < 2.2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  -0.8648310 -0.8544571
## sample estimates:
##        cor 
## -0.8597327
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{par}\NormalTok{(}\DataTypeTok{mfrow =} \KeywordTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{), }\DataTypeTok{mar=}\KeywordTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\KeywordTok{plot}\NormalTok{(LTR_regression)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A06_GLMs_files/figure-latex/linear.regression-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{par}\NormalTok{(}\DataTypeTok{mfrow =} \KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{7}
\tightlist
\item
  Interpret your model results in words. Include how much of the
  variability in temperature is explained by changes in depth, the
  degrees of freedom on which this finding is based, and the statistical
  significance of the result. Also mention how much temperature is
  predicted to change for every 1m change in depth.
\end{enumerate}

\begin{quote}
Answer: With a correlation coefficient of -0.859, there is a strong
negative correlation between temperature and depth (lower temperatures
at greater depths). With an R-squared value of 0.7391, this model
explains 73.9\% of the total variance in temperature. This model has
9720 degrees of freedom, meaning a very large sample size. The result is
statistically significant because the p value is 2.2e-16, which is much
less than 0.05. For every 1m change in depth, temperature will decrease
by 1.95 degrees Celcius.
\end{quote}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{multiple-regression}{%
\subsection{Multiple regression}\label{multiple-regression}}

Let's tackle a similar question from a different approach. Here, we want
to explore what might the best set of predictors for lake temperature in
July across the monitoring period at the North Temperate Lakes LTER.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{8}
\item
  Run an AIC to determine what set of explanatory variables (year4,
  daynum, depth) is best suited to predict temperature.
\item
  Run a multiple regression on the recommended set of variables.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#9}
\NormalTok{NTL_AIC <-}\StringTok{ }\KeywordTok{lm}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ NTL_Processed, temperature_C }\OperatorTok{~}\StringTok{ }\NormalTok{year4 }\OperatorTok{+}\StringTok{ }\NormalTok{daynum }\OperatorTok{+}\StringTok{ }\NormalTok{depth)}

\KeywordTok{step}\NormalTok{(NTL_AIC)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Start:  AIC=26016.31
## temperature_C ~ year4 + daynum + depth
## 
##          Df Sum of Sq    RSS   AIC
## <none>                141118 26016
## - year4   1        80 141198 26020
## - daynum  1      1333 142450 26106
## - depth   1    403925 545042 39151
\end{verbatim}

\begin{verbatim}
## 
## Call:
## lm(formula = temperature_C ~ year4 + daynum + depth, data = NTL_Processed)
## 
## Coefficients:
## (Intercept)        year4       daynum        depth  
##    -6.45556      0.01013      0.04134     -1.94726
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#10}

\NormalTok{NTLmultregression <-}\StringTok{ }\KeywordTok{lm}\NormalTok{(}\DataTypeTok{data=}\NormalTok{NTL_Processed, temperature_C }\OperatorTok{~}\StringTok{ }\NormalTok{year4 }\OperatorTok{+}\StringTok{ }\NormalTok{daynum }\OperatorTok{+}\StringTok{ }\NormalTok{depth)}

\KeywordTok{summary}\NormalTok{(NTLmultregression)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = temperature_C ~ year4 + daynum + depth, data = NTL_Processed)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -9.6517 -2.9937  0.0855  2.9692 13.6171 
## 
## Coefficients:
##              Estimate Std. Error  t value Pr(>|t|)    
## (Intercept) -6.455560   8.638808   -0.747   0.4549    
## year4        0.010131   0.004303    2.354   0.0186 *  
## daynum       0.041336   0.004315    9.580   <2e-16 ***
## depth       -1.947264   0.011676 -166.782   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 3.811 on 9718 degrees of freedom
## Multiple R-squared:  0.7417, Adjusted R-squared:  0.7417 
## F-statistic:  9303 on 3 and 9718 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{par}\NormalTok{(}\DataTypeTok{mfrow =} \KeywordTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{), }\DataTypeTok{mar=}\KeywordTok{c}\NormalTok{(}\DecValTok{4}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{4}\NormalTok{))}
\KeywordTok{plot}\NormalTok{(NTLmultregression)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A06_GLMs_files/figure-latex/temperature.model-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{par}\NormalTok{(}\DataTypeTok{mfrow =} \KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{10}
\tightlist
\item
  What is the final set of explanatory variables that the AIC method
  suggests we use to predict temperature in our multiple regression? How
  much of the observed variance does this model explain? Is this an
  improvement over the model using only depth as the explanatory
  variable?
\end{enumerate}

\begin{quote}
Answer: When running the AIC, it appears that all three variables should
be used to suggest change in temperature. This is because the ``Call''
function shows that all three are included. -With an R squared value of
0.74, this explains that 74\% of the variability of temperature can be
explained by year, daynum, and depth. Each of the three p values is less
than 0.05. -When using only depth as the explanatory variable, there R
squared was 0.73. This means that there is only a slight improvement
because ours increased to only 0.74
\end{quote}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{analysis-of-variance}{%
\subsection{Analysis of Variance}\label{analysis-of-variance}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{11}
\tightlist
\item
  Now we want to see whether the different lakes have, on average,
  different temperatures in the month of July. Run an ANOVA test to
  complete this analysis. (No need to test assumptions of normality or
  similar variances.) Create two sets of models: one expressed as an
  ANOVA models and another expressed as a linear model (as done in our
  lessons).
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#12}

\CommentTok{#ANOVA model}
\NormalTok{NTL_anova<-}\StringTok{ }\KeywordTok{aov}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ NTL_Processed, temperature_C }\OperatorTok{~}\StringTok{ }\NormalTok{lakename)}

\KeywordTok{summary}\NormalTok{(NTL_anova)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##               Df Sum Sq Mean Sq F value Pr(>F)    
## lakename       8  21214  2651.8   49.04 <2e-16 ***
## Residuals   9713 525188    54.1                   
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(NTL_anova)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A06_GLMs_files/figure-latex/anova.model-1.pdf}
\includegraphics{A06_GLMs_files/figure-latex/anova.model-2.pdf}
\includegraphics{A06_GLMs_files/figure-latex/anova.model-3.pdf}
\includegraphics{A06_GLMs_files/figure-latex/anova.model-4.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Linear Model}
\NormalTok{NTL_anova2 <-}\StringTok{ }\KeywordTok{lm}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ NTL_Processed, temperature_C }\OperatorTok{~}\StringTok{ }\NormalTok{lakename)}

\KeywordTok{summary}\NormalTok{(NTL_anova2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = temperature_C ~ lakename, data = NTL_Processed)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -10.766  -6.592  -2.692   7.634  23.832 
## 
## Coefficients:
##                          Estimate Std. Error t value Pr(>|t|)    
## (Intercept)               17.6731     0.6741  26.218  < 2e-16 ***
## lakenameCrampton Lake     -2.3212     0.7902  -2.938  0.00332 ** 
## lakenameEast Long Lake    -7.4054     0.7143 -10.367  < 2e-16 ***
## lakenameHummingbird Lake  -6.8998     0.9594  -7.192 6.88e-13 ***
## lakenamePaul Lake         -3.8813     0.6891  -5.633 1.82e-08 ***
## lakenamePeter Lake        -4.3710     0.6878  -6.355 2.18e-10 ***
## lakenameTuesday Lake      -6.6073     0.7002  -9.437  < 2e-16 ***
## lakenameWard Lake         -3.2145     0.9594  -3.350  0.00081 ***
## lakenameWest Long Lake    -6.0876     0.7115  -8.556  < 2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 7.353 on 9713 degrees of freedom
## Multiple R-squared:  0.03883,    Adjusted R-squared:  0.03803 
## F-statistic: 49.04 on 8 and 9713 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot}\NormalTok{(NTL_anova2)}
\end{Highlighting}
\end{Shaded}

\includegraphics{A06_GLMs_files/figure-latex/anova.model-5.pdf}
\includegraphics{A06_GLMs_files/figure-latex/anova.model-6.pdf}
\includegraphics{A06_GLMs_files/figure-latex/anova.model-7.pdf}
\includegraphics{A06_GLMs_files/figure-latex/anova.model-8.pdf}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{12}
\tightlist
\item
  Is there a significant difference in mean temperature among the lakes?
  Report your findings.
\end{enumerate}

\begin{quote}
Answer: Yes there is a significant difference in mean temperatures
because the p value is less than 0.05.
\end{quote}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{13}
\tightlist
\item
  Create a graph that depicts temperature by depth, with a separate
  color for each lake. Add a geom\_smooth (method = ``lm'', se = FALSE)
  for each lake. Make your points 50 \% transparent. Adjust your y axis
  limits to go from 0 to 35 degrees. Clean up your graph to make it
  pretty.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#14.}

\NormalTok{Plot_temp_lakes <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(NTL_Processed, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{depth, }\DataTypeTok{y=}\NormalTok{temperature_C, }\DataTypeTok{color=}\NormalTok{lakename)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_point}\NormalTok{(}\DataTypeTok{alpha=}\FloatTok{0.5}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_smooth}\NormalTok{(}\DataTypeTok{method=}\StringTok{"lm"}\NormalTok{, }\DataTypeTok{se=}\OtherTok{FALSE}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ylim}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{35}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{xlab}\NormalTok{(}\StringTok{"Depth"}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{(}\StringTok{"Temperature in Celcius"}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.text.x =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{angle=}\DecValTok{90}\NormalTok{))}
  

\KeywordTok{print}\NormalTok{(Plot_temp_lakes)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula 'y ~ x'
\end{verbatim}

\begin{verbatim}
## Warning: Removed 73 rows containing missing values (geom_smooth).
\end{verbatim}

\includegraphics{A06_GLMs_files/figure-latex/scatterplot.2-1.pdf}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{14}
\tightlist
\item
  Use the Tukey's HSD test to determine which lakes have different
  means.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#15}

\NormalTok{NTL_anova_}\DecValTok{3}\NormalTok{<-}\StringTok{ }\KeywordTok{aov}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ NTL_Processed, temperature_C }\OperatorTok{~}\StringTok{ }\NormalTok{lakename)}

\KeywordTok{TukeyHSD}\NormalTok{(NTL_anova_}\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = temperature_C ~ lakename, data = NTL_Processed)
## 
## $lakename
##                                          diff        lwr        upr     p adj
## Crampton Lake-Central Long Lake    -2.3212225 -4.7727515  0.1303066 0.0801309
## East Long Lake-Central Long Lake   -7.4054440 -9.6215318 -5.1893561 0.0000000
## Hummingbird Lake-Central Long Lake -6.8998334 -9.8763946 -3.9232722 0.0000000
## Paul Lake-Central Long Lake        -3.8813120 -6.0191419 -1.7434822 0.0000007
## Peter Lake-Central Long Lake       -4.3710346 -6.5048955 -2.2371736 0.0000000
## Tuesday Lake-Central Long Lake     -6.6072831 -8.7795517 -4.4350145 0.0000000
## Ward Lake-Central Long Lake        -3.2144886 -6.1910498 -0.2379273 0.0229685
## West Long Lake-Central Long Lake   -6.0875867 -8.2949346 -3.8802388 0.0000000
## East Long Lake-Crampton Lake       -5.0842215 -6.5587481 -3.6096949 0.0000000
## Hummingbird Lake-Crampton Lake     -4.5786109 -7.0531008 -2.1041211 0.0000003
## Paul Lake-Crampton Lake            -1.5600896 -2.9141574 -0.2060217 0.0106305
## Peter Lake-Crampton Lake           -2.0498121 -3.3976050 -0.7020192 0.0000841
## Tuesday Lake-Crampton Lake         -4.2860606 -5.6938725 -2.8782488 0.0000000
## Ward Lake-Crampton Lake            -0.8932661 -3.3677559  1.5812237 0.9713958
## West Long Lake-Crampton Lake       -3.7663643 -5.2277226 -2.3050060 0.0000000
## Hummingbird Lake-East Long Lake     0.5056106 -1.7358512  2.7470723 0.9988025
## Paul Lake-East Long Lake            3.5241319  2.6670727  4.3811912 0.0000000
## Peter Lake-East Long Lake           3.0344094  2.1872987  3.8815201 0.0000000
## Tuesday Lake-East Long Lake         0.7981609 -0.1415120  1.7378337 0.1721160
## Ward Lake-East Long Lake            4.1909554  1.9494937  6.4324171 0.0000002
## West Long Lake-East Long Lake       1.3178572  0.2997124  2.3360021 0.0019544
## Paul Lake-Hummingbird Lake          3.0185213  0.8543999  5.1826428 0.0005172
## Peter Lake-Hummingbird Lake         2.5287988  0.3685979  4.6889997 0.0086420
## Tuesday Lake-Hummingbird Lake       0.2925503 -1.9055981  2.4906986 0.9999773
## Ward Lake-Hummingbird Lake          3.6853448  0.6898445  6.6808451 0.0043115
## West Long Lake-Hummingbird Lake     0.8122467 -1.4205745  3.0450678 0.9700210
## Peter Lake-Paul Lake               -0.4897225 -1.1036180  0.1241730 0.2442990
## Tuesday Lake-Paul Lake             -2.7259711 -3.4623514 -1.9895907 0.0000000
## Ward Lake-Paul Lake                 0.6668235 -1.4972980  2.8309450 0.9895659
## West Long Lake-Paul Lake           -2.2062747 -3.0404749 -1.3720745 0.0000000
## Tuesday Lake-Peter Lake            -2.2362485 -2.9610258 -1.5114713 0.0000000
## Ward Lake-Peter Lake                1.1565460 -1.0036549  3.3167469 0.7703831
## West Long Lake-Peter Lake          -1.7165522 -2.5405279 -0.8925764 0.0000000
## Ward Lake-Tuesday Lake              3.3927945  1.1946462  5.5909429 0.0000597
## West Long Lake-Tuesday Lake         0.5196964 -0.3991749  1.4385677 0.7121762
## West Long Lake-Ward Lake           -2.8730982 -5.1059193 -0.6402770 0.0021521
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{NTL_anova_comparison <-}\StringTok{ }\KeywordTok{HSD.test}\NormalTok{(NTL_anova_}\DecValTok{3}\NormalTok{, }\StringTok{"lakename"}\NormalTok{, }\DataTypeTok{group =} \OtherTok{TRUE}\NormalTok{)}
\NormalTok{NTL_anova_comparison}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $statistics
##    MSerror   Df     Mean       CV
##   54.07064 9713 12.70646 57.87035
## 
## $parameters
##    test   name.t ntr StudentizedRange alpha
##   Tukey lakename   9         4.387505  0.05
## 
## $means
##                   temperature_C      std    r Min  Max    Q25   Q50    Q75
## Central Long Lake      17.67311 4.273404  119 8.9 26.8 14.400 18.40 21.350
## Crampton Lake          15.35189 7.244773  318 5.0 27.5  7.525 16.90 22.300
## East Long Lake         10.26767 6.766804  968 4.2 34.1  4.975  6.50 15.925
## Hummingbird Lake       10.77328 7.017845  116 4.0 31.5  5.200  7.00 15.625
## Paul Lake              13.79180 7.291951 2643 4.7 27.7  6.500 12.40 21.400
## Peter Lake             13.30207 7.667550 2892 4.0 27.0  5.600 11.40 21.500
## Tuesday Lake           11.06583 7.694274 1507 0.3 27.7  4.400  6.80 19.400
## Ward Lake              14.45862 7.409079  116 5.7 27.6  7.200 12.55 23.200
## West Long Lake         11.58552 6.963995 1043 4.0 25.7  5.400  8.00 18.800
## 
## $comparison
## NULL
## 
## $groups
##                   temperature_C groups
## Central Long Lake      17.67311      a
## Crampton Lake          15.35189     ab
## Ward Lake              14.45862     bc
## Paul Lake              13.79180      c
## Peter Lake             13.30207      c
## West Long Lake         11.58552      d
## Tuesday Lake           11.06583     de
## Hummingbird Lake       10.77328     de
## East Long Lake         10.26767      e
## 
## attr(,"class")
## [1] "group"
\end{verbatim}

16.From the findings above, which lakes have the same mean temperature,
statistically speaking, as Peter Lake? Does any lake have a mean
temperature that is statistically distinct from all the other lakes?

\begin{quote}
Answer: The lakes that have the same mean temperature as Peter Lake are:
Paul Lake and Ward Lake (according to the HSD.test). According to the
HSD.test, all of the lakes are statistically related to at least one
other lake.
\end{quote}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{16}
\tightlist
\item
  If we were just looking at Peter Lake and Paul Lake. What's another
  test we might explore to see whether they have distinct mean
  temperatures?
\end{enumerate}

\begin{quote}
Answer: If we were just comparing these two lakes, we could use a
two-sample t-test. A two-sample t-test tests the hypothesis that the
mean of two samples is equivalent.This would allow us to compare the
means of each of the two lakes.
\end{quote}

\end{document}
